# version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: Knitted_Toys_Store_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BioKir124578
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - knitted_net

  redis:
    image: redis:8.0.1
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - knitted_net

  backend:
    build:
      context: ./Backend
      dockerfile: DockerfileBackend
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - postgres
      - redis
    ports:
    - "8080:80"
    networks:
      - knitted_net

  frontend:
    build:
      context: ./Frontend
      dockerfile: DockerfileFrontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - knitted_net

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - knitted_net

volumes:
  postgres_data:
  redis_data:

networks:
  knitted_net: